services:
  mongo:
    image: mongo:8.0
    container_name: gds_mongo
    restart: unless-stopped
    ports:
      - '${MONGO_PORT:-27018}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-gds}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-gds}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-coffee_gds_db}
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - mongodata:/data/db
    networks:
      - gds_network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: gds_mongo_express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '${MONGO_EXPRESS_PORT:-8081}:8081'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER:-gds}:${MONGO_ROOT_PASSWORD:-gds}@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-admin}
    networks:
      - gds_network

volumes:
  mongodata:
    driver: local

networks:
  gds_network:
    name: network_gds_ts
    driver: bridge
