#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/gds}
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none

expiration-time=604800