CREATE TABLE tb_requester_absence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    requester_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    updated_by BIGINT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_absence_requester FOREIGN KEY (requester_id) REFERENCES tb_requesters (id) ON DELETE CASCADE,
    CONSTRAINT fk_absence_user FOREIGN KEY (updated_by) REFERENCES tb_users (user_id) ON DELETE SET NULL,
    CONSTRAINT chk_requester_absence_dates CHECK (start_date <= end_date)
);

CREATE INDEX idx_requester_absence_lookup ON tb_requester_absence (requester_id, start_date, end_date);
