CREATE TABLE tb_roles (
    role_id bigint generated by default as identity,
    name varchar(255),
    primary key (role_id)
);

CREATE TABLE tb_users (
    user_id bigint generated by default as identity,
    birth_date timestamp(6),
    cpf varchar(255) not null,
    email varchar(255) not null,
    password varchar(255),
    name varchar(255),
    phone varchar(255),
    status INT CHECK (status in (1, 0)) NOT NULL DEFAULT 1,
    primary key (user_id),
    CONSTRAINT unique_cpf UNIQUE (cpf),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE tb_users_roles (
    user_id bigint not null,
    role_id bigint not null,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES tb_users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (role_id) REFERENCES tb_roles(role_id) ON DELETE SET NULL
);
