CREATE TABLE tb_roles (
    role_id bigint generated by default as identity,
    name varchar(255),
    primary key (role_id)
);

CREATE TABLE tb_users (
    user_id uuid not null,
    birth_date timestamp(6),
    cpf varchar(255) not null,
    email varchar(255) not null,
    password varchar(255),
    position varchar(255) check (position in ('PEDIATRICIAN','GENERAL_PRACTITIONER','SECRETARY')),
    username varchar(255), primary key (user_id),
    CONSTRAINT unique_cpf UNIQUE (cpf),
    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT unique_email UNIQUE (username),
);

CREATE TABLE tb_users_roles (
    user_id uuid not null,
    role_id bigint not null,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES tb_users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (role_id) REFERENCES tb_roles(role_id) ON DELETE SET NULL
);
