CREATE TABLE tb_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    observations TEXT NULL,
    status VARCHAR(15) CHECK (status in ('ACTIVE', 'INACTIVE')) NOT NULL DEFAULT 'ACTIVE',
    PRIMARY KEY (id)
);

CREATE TABLE tb_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    type VARCHAR(15) CHECK (type IN ('MEDICAL_OFFICE')) NULL DEFAULT 'MEDICAL_OFFICE',
    status VARCHAR(15) CHECK (status IN ('ACTIVE', 'INACTIVE')) NOT NULL DEFAULT 'ACTIVE',
    section_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_room_section FOREIGN KEY (section_id) REFERENCES tb_sections (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE tb_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(45) NOT NULL,
    status VARCHAR(15) CHECK (status IN('ACTIVE', 'INACTIVE')) NOT NULL DEFAULT 'ACTIVE',
    PRIMARY KEY (id)
);

CREATE TABLE tb_requesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    contact_number VARCHAR(11) NULL,
    type VARCHAR(15) CHECK (type IN ('EMPLOYEE', 'STUDENT', 'VISITOR')) NULL DEFAULT 'EMPLOYEE',
    status VARCHAR(15) CHECK (status IN ('ACTIVE', 'INACTIVE')) NOT NULL DEFAULT 'ACTIVE',
    position_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_requester_position FOREIGN KEY (position_id) REFERENCES tb_positions (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE tb_reservations (
    room_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    observations TEXT NULL,
    status VARCHAR(15) CHECK (status IN ('REQUESTED', 'CANCELLED')) NOT NULL DEFAULT 'REQUESTED',
    PRIMARY KEY (room_id, requester_id),
    CONSTRAINT fk_reservation_room FOREIGN KEY (room_id) REFERENCES tb_rooms (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_reservation_requester FOREIGN KEY (requester_id) REFERENCES tb_requesters (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE tb_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    week_day VARCHAR(15) CHECK (week_day IN ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY')) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status VARCHAR(15) CHECK (status IN ('ACTIVE', 'VACATION')) NOT NULL,
    requester_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_schedule_requester FOREIGN KEY (requester_id) REFERENCES tb_requesters (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);