CREATE TABLE tb_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    observations TEXT NULL,
    status INT CHECK (status in (1, 0)) NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);

CREATE TABLE tb_room_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    status INT CHECK (status in (1, 0)) NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);

CREATE TABLE tb_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    status INT CHECK (status IN (1, 0)) NOT NULL DEFAULT 1,
    section_id BIGINT NOT NULL,
    room_type_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_room_section FOREIGN KEY (section_id) REFERENCES tb_sections (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_room_type FOREIGN KEY (room_type_id) REFERENCES tb_room_types (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE tb_requester_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(15) CHECK (name IN ('Funcionário', 'Estudante', 'Visitante')) NULL DEFAULT 'Funcionário',
    position VARCHAR(60) NULL,
    status INT CHECK (status in (1, 0)) NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);

CREATE TABLE tb_requesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    contact_number VARCHAR(11) NULL,
    status INT CHECK (status in (1, 0)) NOT NULL DEFAULT 1,
    requester_type_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_requester_type FOREIGN KEY (requester_type_id) REFERENCES tb_requester_types (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE tb_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    observations TEXT NULL,
    status VARCHAR(15) CHECK (status IN ('Aprovada', 'Cancelada')) NOT NULL DEFAULT 'Aprovada',
    room_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_reservation_room FOREIGN KEY (room_id) REFERENCES tb_rooms (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_reservation_requester FOREIGN KEY (requester_id) REFERENCES tb_requesters (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);