name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate private and public RSA Key
        run: |
          openssl genpkey -algorithm RSA -out src/main/resources/app.key -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in src/main/resources/app.key -out src/main/resources/app.pub

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Build Maven
        run: |
          ./mvnw clean package -q -Dmaven.test.skip

      - name: Build Docker Images
        run: |
          docker build -t clinic_room_backend -f Dockerfile.prod .

      - name: Tag Docker Images
        run: |
          docker tag clinic_room_backend ${{ secrets.DOCKER_USERNAME }}/clinic_room_backend:clinic_room_backend

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/clinic_room_backend:clinic_room_backend

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to EC2
        run: |
          sshpass -p "${{ secrets.HETZNER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.HETZNER_HOST }} << 'EOF'
          sudo docker stop app || true
          sudo docker rm app || true
          sudo docker network create network_cr || true
          
          echo "APP_PROFILE=prod" > .env
          echo "DB_URL=jdbc:postgresql://${{ secrets.RDS_ENDPOINT }}:5432/gds" >> .env
          echo "DB_USERNAME=${{ secrets.RDS_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> .env
          echo "EXPIRATION_TIME=${{ secrets.EXPIRATION_TIME }}" >> .env
          echo "ADMIN_CPF=${{ secrets.ADMIN_CPF }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/clinic_room_backend:clinic_room_backend
          
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/clinic_room_backend:clinic_room_backend
          sudo docker run --env-file .env -d --network=network_cr --name app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/clinic_room_backend:clinic_room_backend
          sudo docker update --restart unless-stopped app
          
          EOF
